### ISSUE TITLE
New feature - stars

### ISSUE THREAD

**Issue by vollowx** [popov895/Clipman#11]
I want a new feature like ***'collections' or 'stars'***, can store clip histories I stared forever till I delete it, and thay has the top position.

Extension 'Clip History' has this function, and I would like this extension can also has this function.

:P

**Comment by popov895** [comment]
Sorry, but the Clipman was intended to be a lightweight and simple clipboard manager extension with basic functionality, and having "favorites" looks superfluous to me. Perhaps someday I will change my mind and implement this feature, but not in the near future.

As you have noticed, there are other extensions that already have the functionality you requested, so you can use them.
