### ISSUE TITLE
Error installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by gimmy** [popov895/Clipman#14]
After upgrading the extension from the website, it shows now an error on the website. 
I tried to remove the extension and reinstall it, but the error remains (the extension does not start).
I have tried to install the extension manually, but it is not shown in the list after `gnome-extension list` and the command in the README to enable the extension returns
```
Extension “clipman@popov895.ukr.net” does not exist
```

**Comment by popov895** [comment]
Have you restarted your session after updating the extension?

**Comment by gimmy** [comment]
Yes, now it works.
