### ISSUE TITLE
Favorite items disappear after reboot

### ISSUE THREAD

**Issue by inbalboa** [popov895/Clipman#18]
Hi!
Items saved as favorites do not survive computer reboot.
Gnome 44.

Thank you!

**Comment by popov895** [comment]
This is by design, Clipman doesn't store any data between sessions. Favorite items are placed above the regular items and aren't deleted when you clear the history, that's all.

**Comment by bittner** [comment]
Are there any plans to keep the clipboard items persisted? A user option, maybe?

I'd prefer to have all of them persisted, so that they survive a reboot, system failure or shutdown, even the ones that are not favorites.

**Comment by popov895** [comment]
There are no such plans in the near future.
