### ISSUE TITLE
History Missing!

### ISSUE THREAD

**Issue by sallyhaj** [popov895/Clipman#2]
Hello there,

When the screen goes to screensaver, or reboot the system, all the history gone from the list.
I'm using Fedora 36/Gnome 42 on aarch64/arm64 system.

Thank you.

**Comment by popov895** [comment]
This extension doesn't save clipboard history between reboots, so this is intentional. Losing data when locking the screen is fixed in version 7.

Thanks for your attention!

**Comment by sallyhaj** [comment]
thank you
