### ISSUE TITLE
feauture - keyboard shortcuts for Prev and Next entries

### ISSUE THREAD

**Issue by xalt7x** [popov895/Clipman#27]
Some clipboard managers have useful ability to switch between entries using keyboard shortcuts.
If user knows recent entries, such shortcuts would significantly speed up their selection. For example, instead of using Super+z and arrows, one could use Super+Shift+Z (previous entry) and Super+Shift+X (next entry)
During switch user could be informed about current entry with notifications (which shouldn't be shown in "Do not disturb" and "Private" modes).

**Comment by popov895** [comment]
I'm not sure I understand you correctly. Could you please explain in more detail what you mean by recent, next and previous entries? Which clipboard managers have this ability?

**Comment by xalt7x** [comment]
Please see my screencast below. I'm switching history elements in the list with shortcuts.

[Screencast from 2023-09-13 09-36-24.webm](https://github.com/popov895/Clipman/assets/44649402/7c1a71b0-bdfc-404e-9035-2dd281debb83)

I've used [Clipboard History](https://github.com/SUPERCILEX/gnome-clipboard-history) extension (fork of the [Cliboard Indicator](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator)). KDE's Klipper also supports it.

**Comment by xalt7x** [comment]
Please see my screencast with the [Clipboard History](https://github.com/SUPERCILEX/gnome-clipboard-history) extension.  
There I switch history elements in the list using keyboard shortcuts.

[Screencast from 2023-09-13 09-36-24.webm](https://github.com/popov895/Clipman/assets/44649402/7c1a71b0-bdfc-404e-9035-2dd281debb83)

**Comment by popov895** [comment]
I'm afraid that currently it's not possible to implement such a feature. As you can see, in this extension the current entry is always on top, so there's no next entry. Also, activating the previous entry (which is below the current one) will always swap it with the current one.

In truth, I don't see any real use cases for this feature. IMO only a few people would use it.
