### ISSUE TITLE
Add an action to upload to pastebin

### ISSUE THREAD

**Issue by bbhtt** [popov895/Clipman#28]
gpaste has this function in the daemon that spawns a subprocess and calls `wgetpaste` (hardcoded) to send the current copied item. `wgetpaste` handles the upload and outputs an url which is again copied back to the selection.

This would be nice to have in the action menu.

It can be hardcoded or an option in preferences for the binary to spawn would be great.

Thanks!

**Comment by popov895** [comment]
Interesting idea. I'll think about what I can do for this.

**Comment by popov895** [comment]
Unfortunately, pastebin [has a limitation](https://pastebin.com/faq#11a) of 20 new pastes per 24 hours. Maybe there is a better analogue?

**Comment by bbhtt** [comment]
Are you trying to implement it directly? In that case I think https://0x0.st/ or https://x0.at/ might be better. Both can handle text, file, images etc. and it's a curl call. Both has a bunch of instances available

**Comment by popov895** [comment]
I chose [dpaste.com](https://dpaste.com) because it's 17 years old, has a simple API and doesn't require API key.

Fixed in version 49.

**Comment by bbhtt** [comment]
Thanks

**Comment by bbhtt** [comment]
Hmm I'm on v51 but not seeing the option to paste, any idea?

![image](https://github.com/popov895/Clipman/assets/62639087/668812da-57d8-4a3a-a375-75376585016d)

I have this option though which I guess is the paste expiration limit

![image](https://github.com/popov895/Clipman/assets/62639087/19c4ad95-c13c-4281-b0cb-ee2be9a9aa60)

**Comment by bbhtt** [comment]
Ah nvm looks like it was renamed in https://github.com/popov895/Clipman/commit/4521be2a5553479cb4229d39389b5e68edb269a9

**Comment by popov895** [comment]
Yep, "Paste to Pastebin" didn't pass moderation on EGO.
