### ISSUE TITLE
Adjust height and width of default window

### ISSUE THREAD

**Issue by thisisazharul** [popov895/Clipman#30]
The default window width of the Clipman extension is a bit large for me, and couldn't find any option to adjust it. It would be great if there was an option to adjust the height and width of the default window.

**Expected Behavior:**

The user should be able to adjust the height and width of the Clipman window to their liking.

**Actual Behavior:**

The height and width of the Clipman window cannot be adjusted.

**Comment by popov895** [comment]
Can you provide screenshots?

**Comment by popov895** [comment]
Fixed in version 51.
