### ISSUE TITLE
Feature Request: Persistent Clipboard History Between Seessions

### ISSUE THREAD

**Issue by g0ne150** [popov895/Clipman#36]
I'm a big fan of Clipman, and I find it incredibly useful. However, I have a feature request that would make it even better. Currently, the clipboard history is lost upon reboot or logout, and I think it would be a valuable improvement to make the clipboard history persist across sessions.

I kindly request the implementation of a feature that allows the clipboard history to be saved and restored even after system reboots or user logouts. This would greatly enhance the usability of the extension and make it more convenient for users who rely on it for their daily tasks.

One possible implementation suggestion is to create a dedicated data file that stores clipboard history entries and is automatically loaded upon Clipman startup. This way, the clipboard history can be restored each time the user logs in or the system reboots.

If there are any technical constraints, considerations, or challenges associated with this feature request, please let me know. I'd be happy to assist or test any proposed changes to help make this feature a reality.

Thank you for your work on the Clipman extension, and I hope you will consider this feature request. If you have any questions or need further clarification, please feel free to ask.

**Comment by popov895** [comment]
Fixed in version 55.
