### ISSUE TITLE
Support for Kagi search

### ISSUE THREAD

**Issue by snaggen** [popov895/Clipman#37]
I see that you do not have support for the Kagi search engine, the search url is:
```
https://kagi.com/search?q=%s
```

**Comment by popov895** [comment]
This search engine is paid, so I can't add it to the Clipman. However, you can add it manually: open the settings, select `Other` in the list of search engines and provide the required URL.

**Comment by snaggen** [comment]
But google and others are paid for by your personal data. I prefer paying with money. Neither Google or Bing is free.

**Comment by popov895** [comment]
Well, for a donation of $500 I will add them to the list of search engines, and for a donation of $1000 I will even make it the default search engine 😉
