### ISSUE TITLE
Wishlist: feature request

### ISSUE THREAD

**Issue by juarezr** [popov895/Clipman#38]
Thanks for the effort on this awesome extension.

I use it the whole day and it helps me to increase my productivity a lot!

## Feature requests

Some things I miss:

### Keyboard shortcuts 

- For swapping current clipboard entry with previous or previous <N> entry. 
  - It's useful when you must copy more than one text/line and sort/invert/transpose them in an order diverse from the copy. It speeds up the handling by not having to navigate across the items in the menu.
- Paste as plain text:
  - Useful when copying/pasting between browser/rich text and plain text.

### Features

- Display the menu popup near the caret/focused field in the focused window below the top bar menu icons.
  - It causes confusion and distraction if the focused window is in another monitor than the extension icon.

**Comment by popov895** [comment]
> For swapping current clipboard entry with previous or previous entry

See https://github.com/popov895/Clipman/issues/27.

> Paste as plain text

This extension keeps the clipboard history as plain text, so when you click on a history entry, the clipboard gets the text without formatting. Therefore, there's nothing to fix/improve. In most cases, you can paste text without formatting using the keyboard shortcut `Ctrl+Shift+V`.

> Display the menu popup near the caret/focused field in the focused window below the top bar menu icons

I'm afraid that it's hard/impossible to implement.

And please don't include more than one feature per feature request.
