### ISSUE TITLE
Ignoring KeePassXC sometimes doesn't work

### ISSUE THREAD

**Issue by sith-on-mars** [popov895/Clipman#41]
Clipman is designed to ignore passwords from KeePassXC, but this stopped working randomly. Would you be able to have a look please? I'm using the Flatpak version of KeePassXC.

**Comment by popov895** [comment]
Which OS and GNOME version?

**Comment by sith-on-mars** [comment]
Fedora Silverblue 39, Gnome 45. Thanks!

**Comment by popov895** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10048

**Comment by popov895** [comment]
Just to note, this is a bug in GNOME. I can only recommend you to use the native version of the KeePassXC (from the repository) or use the private mode when copying passwords.
