### ISSUE TITLE
Cannot set shortcut to Super+V

### ISSUE THREAD

**Issue by luco5826** [popov895/Clipman#7]
Awesome extension, used it a lot on the previous Pop!_OS version but with the current one I'm unable to set the shortcut to Super+V

Whenever I press Super to set the keybinding, the button resets and I cannot press V (neither any other key)

System: Pop!_OS 22.04 LTS, Gnome 42.1 (X11)

**Comment by popov895** [comment]
Yes, I am aware of this issue on GNOME 42 and X11. I'm already looking for a workaround for this. For now, you can set this shortcut on Wayland and then switch back to X11, or you can use the following command:
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/clipman@popov895.ukr.net/schemas/ set org.gnome.shell.extensions.clipman toggle-menu-shortcut "['<Super>V']"
```

**Comment by popov895** [comment]
Fixed in version 11
